name: CI

on: [push]

jobs:
  phpunit:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        php-version: ['8.2', '8.3', '8.4']
        dependencies: ['lowest', 'highest']
    name: 'PHPUnit'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl
          coverage: xdebug
          ini-values: xdebug.max_nesting_level=2048
      - name: Composer
        uses: "ramsey/composer-install@v2"
        with:
          dependency-versions: ${{ matrix.dependencies }}
      - name: PHPUnit
        run: vendor/bin/phpunit --coverage-clover=coverage.clover
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  psalm:
    uses: innmind/github-workflows/.github/workflows/psalm-matrix.yml@main
  cs:
    uses: innmind/github-workflows/.github/workflows/cs.yml@main
    with:
      php-version: '8.2'
